# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12YMQOwGsTYPwITFIu1jOWs4su8ipD76V
"""

import pandas as pd
import numpy as np


cgm_data=pd.read_csv('CGMData.csv',low_memory=False,usecols=['Date','Time','Sensor Glucose (mg/dL)'])
insulin_data=pd.read_csv('InsulinData.csv',low_memory=False)

cgm_data['date_time_stamp']=pd.to_datetime(cgm_data['Date'] + ' ' + cgm_data['Time'])

removeXdate=cgm_data[cgm_data['Sensor Glucose (mg/dL)'].isna()]['Date'].unique()

cgm_data=cgm_data.set_index('Date').drop(index=removeXdate).reset_index()

cgm_test=cgm_data.copy()

cgm_test=cgm_test.set_index(pd.DatetimeIndex(cgm_data['date_time_stamp']))

insulin_data['date_time_stamp']=pd.to_datetime(insulin_data['Date'] + ' ' + insulin_data['Time'])


start_of_auto_mode=insulin_data.sort_values(by='date_time_stamp',ascending=True).loc[insulin_data['Alarm']=='AUTO MODE ACTIVE PLGM OFF'].iloc[0]['date_time_stamp']
auto_mode_data_df=cgm_data.sort_values(by='date_time_stamp',ascending=True).loc[cgm_data['date_time_stamp']>=start_of_auto_mode]
manual_mode_data_df=cgm_data.sort_values(by='date_time_stamp',ascending=True).loc[cgm_data['date_time_stamp']<start_of_auto_mode]


auto_mode_data_df_date_index=auto_mode_data_df.copy()
auto_mode_data_df_date_index=auto_mode_data_df_date_index.set_index('date_time_stamp')
list1=auto_mode_data_df_date_index.groupby('Date')['Sensor Glucose (mg/dL)'].count().where(lambda x:x>0.8*288).dropna().index.tolist()
auto_mode_data_df_date_index=auto_mode_data_df_date_index.loc[auto_mode_data_df_date_index['Date'].isin(list1)]


autoXhyperglycemiaXwholeday=(auto_mode_data_df_date_index.between_time('0:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[auto_mode_data_df_date_index['Sensor Glucose (mg/dL)']>180].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)

autoXhyperglycemiaCriticalXwholeday=(auto_mode_data_df_date_index.between_time('0:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[auto_mode_data_df_date_index['Sensor Glucose (mg/dL)']>250].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)

autoXrangeXwholeday=(auto_mode_data_df_date_index.between_time('0:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[(auto_mode_data_df_date_index['Sensor Glucose (mg/dL)']>=70) & (auto_mode_data_df_date_index['Sensor Glucose (mg/dL)']<=180)].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)

autoXrangeSecondaryXwholeday=(auto_mode_data_df_date_index.between_time('0:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[(auto_mode_data_df_date_index['Sensor Glucose (mg/dL)']>=70) & (auto_mode_data_df_date_index['Sensor Glucose (mg/dL)']<=150)].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)

autoXhypoglycemiaLevel1Xwholeday=(auto_mode_data_df_date_index.between_time('0:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[auto_mode_data_df_date_index['Sensor Glucose (mg/dL)']<70].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)

autoXhypoglycemiaLevel2Xwholeday=(auto_mode_data_df_date_index.between_time('0:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[auto_mode_data_df_date_index['Sensor Glucose (mg/dL)']<54].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)



autoXhyperglycemiaXdaytime=(auto_mode_data_df_date_index.between_time('6:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[auto_mode_data_df_date_index['Sensor Glucose (mg/dL)']>180].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)

autoXhyperglycemiaCriticalXdaytime=(auto_mode_data_df_date_index.between_time('6:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[auto_mode_data_df_date_index['Sensor Glucose (mg/dL)']>250].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)

autoXrangeXdaytime=(auto_mode_data_df_date_index.between_time('6:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[(auto_mode_data_df_date_index['Sensor Glucose (mg/dL)']>=70) & (auto_mode_data_df_date_index['Sensor Glucose (mg/dL)']<=180)].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)

autoXrangeSecondaryXdaytime=(auto_mode_data_df_date_index.between_time('6:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[(auto_mode_data_df_date_index['Sensor Glucose (mg/dL)']>=70) & (auto_mode_data_df_date_index['Sensor Glucose (mg/dL)']<=150)].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)

autoXhypoglycemiaLevel1Xdaytime=(auto_mode_data_df_date_index.between_time('6:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[auto_mode_data_df_date_index['Sensor Glucose (mg/dL)']<70].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)

autoXhypoglycemiaLevel2Xdaytime=(auto_mode_data_df_date_index.between_time('6:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[auto_mode_data_df_date_index['Sensor Glucose (mg/dL)']<54].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)



autoXhyperglycemiaXovernight=(auto_mode_data_df_date_index.between_time('0:00:00','05:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[auto_mode_data_df_date_index['Sensor Glucose (mg/dL)']>180].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)

autoXhyperglycemiaCriticalXovernight=(auto_mode_data_df_date_index.between_time('0:00:00','05:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[auto_mode_data_df_date_index['Sensor Glucose (mg/dL)']>250].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)

autoXrangeXOvernight=(auto_mode_data_df_date_index.between_time('0:00:00','05:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[(auto_mode_data_df_date_index['Sensor Glucose (mg/dL)']>=70) & (auto_mode_data_df_date_index['Sensor Glucose (mg/dL)']<=180)].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)

autoXrangeSecondaryXovernight=(auto_mode_data_df_date_index.between_time('0:00:00','05:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[(auto_mode_data_df_date_index['Sensor Glucose (mg/dL)']>=70) & (auto_mode_data_df_date_index['Sensor Glucose (mg/dL)']<=150)].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)

autoXhypoglycemiaLevel1Xovernight=(auto_mode_data_df_date_index.between_time('0:00:00','05:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[auto_mode_data_df_date_index['Sensor Glucose (mg/dL)']<70].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)

autoXhypoglycemiaLevel2Xovernight=(auto_mode_data_df_date_index.between_time('0:00:00','05:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[auto_mode_data_df_date_index['Sensor Glucose (mg/dL)']<54].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)


manual_mode_data_df_index=manual_mode_data_df.copy()
manual_mode_data_df_index=manual_mode_data_df_index.set_index('date_time_stamp')
list2=manual_mode_data_df_index.groupby('Date')['Sensor Glucose (mg/dL)'].count().where(lambda x:x>0.8*288).dropna().index.tolist()
manual_mode_data_df_index=manual_mode_data_df_index.loc[manual_mode_data_df_index['Date'].isin(list2)]


manualXhyperglycemiaXwholeday=(manual_mode_data_df_index.between_time('0:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[manual_mode_data_df_index['Sensor Glucose (mg/dL)']>180].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)

manualXhyperglycemiaCriticalXwholeday=(manual_mode_data_df_index.between_time('0:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[manual_mode_data_df_index['Sensor Glucose (mg/dL)']>250].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)

manualXRangeXwholeday=(manual_mode_data_df_index.between_time('0:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[(manual_mode_data_df_index['Sensor Glucose (mg/dL)']>=70) & (manual_mode_data_df_index['Sensor Glucose (mg/dL)']<=180)].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)

manualXrangeSecondaryXwholeday=(manual_mode_data_df_index.between_time('0:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[(manual_mode_data_df_index['Sensor Glucose (mg/dL)']>=70) & (manual_mode_data_df_index['Sensor Glucose (mg/dL)']<=150)].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)

manualXhypoglycemiaLevel1Xwholeday=(manual_mode_data_df_index.between_time('0:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[manual_mode_data_df_index['Sensor Glucose (mg/dL)']<70].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)

manualXhypoglycemiaLevel2Xwholeday=(manual_mode_data_df_index.between_time('0:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[manual_mode_data_df_index['Sensor Glucose (mg/dL)']<54].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)



manualXhyperglycemiaXdaytime=(manual_mode_data_df_index.between_time('6:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[manual_mode_data_df_index['Sensor Glucose (mg/dL)']>180].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)

manualXhyperglycemiaCriticalXdaytime=(manual_mode_data_df_index.between_time('6:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[manual_mode_data_df_index['Sensor Glucose (mg/dL)']>250].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)

manualXrange_daytime=(manual_mode_data_df_index.between_time('6:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[(manual_mode_data_df_index['Sensor Glucose (mg/dL)']>=70) & (manual_mode_data_df_index['Sensor Glucose (mg/dL)']<=180)].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)

manualXrangeSecondaryXdaytime=(manual_mode_data_df_index.between_time('6:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[(manual_mode_data_df_index['Sensor Glucose (mg/dL)']>=70) & (manual_mode_data_df_index['Sensor Glucose (mg/dL)']<=150)].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)

manualXhypoglycemiaLevel1Xdaytime=(manual_mode_data_df_index.between_time('6:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[manual_mode_data_df_index['Sensor Glucose (mg/dL)']<70].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)

manualXhypoglycemiaLevel2Xdaytime=(manual_mode_data_df_index.between_time('6:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[manual_mode_data_df_index['Sensor Glucose (mg/dL)']<54].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)



manualXhyperglycemiaXovernight=(manual_mode_data_df_index.between_time('0:00:00','05:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[manual_mode_data_df_index['Sensor Glucose (mg/dL)']>180].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)

manualXhyperglycemiaCriticalXovernight=(manual_mode_data_df_index.between_time('0:00:00','05:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[manual_mode_data_df_index['Sensor Glucose (mg/dL)']>250].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)

manualXrangeXovernight=(manual_mode_data_df_index.between_time('0:00:00','05:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[(manual_mode_data_df_index['Sensor Glucose (mg/dL)']>=70) & (manual_mode_data_df_index['Sensor Glucose (mg/dL)']<=180)].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)

manualXrangeSeccondaryXovernight=(manual_mode_data_df_index.between_time('0:00:00','05:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[(manual_mode_data_df_index['Sensor Glucose (mg/dL)']>=70) & (manual_mode_data_df_index['Sensor Glucose (mg/dL)']<=150)].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)

manualXhypoglycemiaLevel1Xovernight=(manual_mode_data_df_index.between_time('0:00:00','05:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[manual_mode_data_df_index['Sensor Glucose (mg/dL)']<70].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)

maualXhypoglycemiaLevel2Xovernight=(manual_mode_data_df_index.between_time('0:00:00','05:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[manual_mode_data_df_index['Sensor Glucose (mg/dL)']<54].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)



results_df = pd.DataFrame({'hyperglycemia_overnight':[ manualXhyperglycemiaXovernight.mean(axis=0),autoXhyperglycemiaXovernight.mean(axis=0)],

'hyperglycemiaCriticalXovernight':[ manualXhyperglycemiaCriticalXovernight.mean(axis=0),autoXhyperglycemiaCriticalXovernight.mean(axis=0)],

'rangeXovernight':[ manualXrangeXovernight.mean(axis=0),autoXrangeXOvernight.mean(axis=0)],

'rangeSecondaryXovernight':[ manualXrangeSeccondaryXovernight.mean(axis=0),autoXrangeSecondaryXovernight.mean(axis=0)],

'hypoglycemiaLevel1Xovernight':[ manualXhypoglycemiaLevel1Xovernight.mean(axis=0),autoXhypoglycemiaLevel1Xovernight.mean(axis=0)],

'hypoglycemiaLevel2Xovernight':[np.nan_to_num(maualXhypoglycemiaLevel2Xovernight.mean(axis=0)),np.nan_to_num(autoXhypoglycemiaLevel2Xovernight.mean(axis=0))],

'hyperglycemiaXdaytime':[ manualXhyperglycemiaXdaytime.mean(axis=0),autoXhyperglycemiaXdaytime.mean(axis=0)],

'hyperglycemiaCriticalXdaytime':[ manualXhyperglycemiaCriticalXdaytime.mean(axis=0),autoXhyperglycemiaCriticalXdaytime.mean(axis=0)],

'rangeXdaytime':[ manualXrange_daytime.mean(axis=0),autoXrangeXdaytime.mean(axis=0)],

'rangeSecondaryXdaytime':[ manualXrangeSecondaryXdaytime.mean(axis=0),autoXrangeSecondaryXdaytime.mean(axis=0)],

'hypoglycemiaLevel1Xdaytime':[ manualXhypoglycemiaLevel1Xdaytime.mean(axis=0),autoXhypoglycemiaLevel1Xdaytime.mean(axis=0)],

'hypoglycemiaLevel2Xdaytime':[ manualXhypoglycemiaLevel2Xdaytime.mean(axis=0),autoXhypoglycemiaLevel2Xdaytime.mean(axis=0)],

'hyperglycemiaXwholeday':[ manualXhyperglycemiaXwholeday.mean(axis=0),autoXhyperglycemiaXwholeday.mean(axis=0)],

'hyperglycemiaCriticalXwholeday':[ manualXhyperglycemiaCriticalXwholeday.mean(axis=0),autoXhyperglycemiaCriticalXwholeday.mean(axis=0)],

'rangeXwholeday':[ manualXRangeXwholeday.mean(axis=0),autoXrangeXwholeday.mean(axis=0)],

'rangeSecondaryXwholeday':[ manualXrangeSecondaryXwholeday.mean(axis=0),autoXrangeSecondaryXwholeday.mean(axis=0)],

'hypoglycemiaLevel1Xwholeday':[ manualXhypoglycemiaLevel1Xwholeday.mean(axis=0),autoXhypoglycemiaLevel1Xwholeday.mean(axis=0)],

'hypoglycemiaLevel2Xwholeday':[ manualXhypoglycemiaLevel2Xwholeday.mean(axis=0),autoXhypoglycemiaLevel2Xwholeday.mean(axis=0)],
 
 'xyz':[1.1,1.1]}, index=['manual_mode','auto_mode'],
    
columns = ['hyperglycemia_overnight', 'hyperglycemiaCriticalXovernight', 'rangeXovernight', 'rangeSecondaryXovernight','hypoglycemiaLevel1Xovernight','hypoglycemiaLevel2Xovernight', 'hyperglycemiaXdaytime',  'hyperglycemiaCriticalXdaytime','rangeXdaytime', 'rangeSecondaryXdaytime','hypoglycemiaLevel1Xdaytime', 'hypoglycemiaLevel2Xdaytime', 'hyperglycemiaXwholeday','hyperglycemiaCriticalXwholeday','rangeXwholeday', 'rangeSecondaryXwholeday','hypoglycemiaLevel1Xwholeday', 'hypoglycemiaLevel2Xwholeday' ,'xyz'])


results_df.to_csv('Results.csv',header=False,index=False)